# Generated by Django 4.1.6 on 2023-02-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name_plural': 'hobbies'},
        ),
    ]
