# Generated by Django 4.1.6 on 2023-02-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_hobby_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='accolade',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
